### PR TITLE
[WIP] Convert old translations to new format.

### PR DESCRIPTION
**Pull request by kaeza**
Converted locale files from old `.txt` format to new `.po` format.

Requesting help from translators before this is merged:

* [ ] French: @Calinou 
* [ ] German: @Xanthin 
* [ ] Italian: Emon (can't find contact info).
* [ ] Malay: @MuhdNurHidayat 
* [ ] Portuguese: @aracnus, (@BrunoMine ?)

### CODE REVIEW

**Comment by BrunoMine** [comment]
I'll work on it.

**Comment by BrunoMine** [comment]
Which license is most suitable for translations?

Also, I would like to know the date of creation of the old `pt.txt` file. 
I could not locate in old commits.

**Comment by kaeza** [comment]
That is a good question. Probably CC-BY-SA or similar.

@VanessaE ?

**Comment by VanessaE** [comment]
I'm okay with any license you want to use for translations - I actually have no idea which is the best.

**Comment by kaeza** [comment]
I think I will merge this as-is for now and let other translators do their thing.

**Pull request closed without merging**
