### PR TITLE
Make computer and printer functional

### PR DESCRIPTION
**Pull request by cheapie**
This turns the desktop computer into a mesecons-less (digilines only) Luacontroller, with a slightly reskinned formspec to match the "computer" theme.

The printer is also now able to print and scan, as long as digilines and memorandum are installed. A message of "scan" will result in it scanning and sending a table back with the data, and sending it a table with values for "text" and "signer" will make it print.

### CODE REVIEW

**Comment by t4im** [comment]
You should not be copying the mesecon luacontroller code among others into other mods.

Either have mesecon override the computers to add the functionality, or let them provide an api.
But security risky code like this must not be duplicated like this. :-1:

**Comment by VanessaE** [comment]
For now, I don't think it can be helped.  If @Jeija wants to add an API, I suppose at that point we could switch to it.

**Comment by cheapie** [comment]
The idea is to make it work without mesecons. VanessaE suggested it as an
alternative to making mesecons' wires a separate mod to the "core" part of
mesecons, which IMO is a better approach.

**Comment by t4im** [comment]
> a separate mod to the "core" part of mesecons, which IMO is a better approach.

That would be better, indeed.

Right now it is creating the mesecon namespace if no mesecons is installed without implementing the full mesecons API. 
Besides this breaking a taboo, it might also break some mods.

**Comment by Jeija** [comment]
> VanessaE suggested it as an alternative to making mesecons' wires a separate mod to the "core" part of mesecons, which IMO is a better approach.

That sounds reasonable, but that would mean people still have to install the full mesecons core mod (without wires) + the luacontroller to make this work. So the idea is just to not have the wires, because they register so many nodes?

My very-long-term-plan for the luacontroller is to split it into two seperate sub-mods of mesecons: The current luacontroller and a web-version of the luacontroller. Now that the HTTP APIs are integrated into the current minetest version, the idea is to have some kind of webpage with a code editor that can be used to write code for the luacontroller. That webpage can also contain sample code snippets and give players the option to publish their code, where it can be rated and reused by others. Every code snippet then has a short ID code that can be entered into the web-luacontroller inside minetest which will automatically update its code via the new HTTP APIs.

Doing this means that I will have to seperate and abstract the sandboxing code from the luacontroller at some point, so it should also be available for e.g. homedcor. For you, that would mean people won't have to install the luacontroller in order to be able to use the homdecor computer. However, that web-controller thing isn't really on top of my to-do list right now. If you still think that separation of the sandboxing code is a good idea, any PRs on mesecons that take care of seperating wires from core (should be easy, there is no technical reason for having wires in core) and abstracting the sandbox away from the luacontroller are welcome. The abstracted luacontroller sandbox may be written a way that doesn't even require the mesecons namespace.

**Comment by cheapie** [comment]
Since it's been pretty much established that this PR (in its current state) is a bad idea, and we've decided on a better way to achieve what this PR was meant to enable (LuaCs without mesecons wires), I'm closing it for now.

**Pull request closed without merging**
