### PR TITLE
Translation to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by afmachado**

### CODE REVIEW

**Comment by VanessaE** [comment]
Can you re-check this pull request please?  I just merged another PR for the same language.

**Comment by afmachado** [comment]
Is it alright now? Sorry for the long time. =P

**Comment by VanessaE** [comment]
I see changes in this pull request that are not related to addition of Russian translations.

Please update your copy of home decor and create a new pull request, or if necessary, you may have to start over.

**Comment by VanessaE** [comment]
(ignore where I wrote "russian")

**Pull request closed without merging**
