### PR TITLE
add setting homedecor.disable_coin_crafting

### PR DESCRIPTION
**Pull request by codexp**
In some cases someone may wish to disable coin crafting, to make coins exclusive for usage with own economy.

server admins can configure it with a setting in minetest.conf:

    homedecor.disable_coin_crafting = yes

### CODE REVIEW

**Comment by redblade7** [comment]
How will this setting affect the soda machine?

**Comment by codexp** [comment]
@redblade7 will have no effect. But coins have to be distributed to players any other way (i.e. through selling).

**Comment by codexp** [comment]
is this correct?

**Comment by VanessaE** [comment]
Is this complete?

**Comment by codexp** [comment]
settings name has been prefixed as stated, there are no more open requests, I assume this as complete.

**Pull request merged**
