### PR TITLE
Simplify integration moreblocks and stairs in building blocks

### PR DESCRIPTION
**Pull request by Jat15**
Stairs replace bbstairs
And and one functions for creates all cut blocks.

### CODE REVIEW

**Comment by VanessaE** [comment]
Too many unrelated changes in your commits.  Please verify whether you really need to rename nodes, and use separate commits for each "category" of changes.  Otherwise your patch is hard to review.

**Comment by Jat15** [comment]
1 commit : 
The renaming is to make the whole homogeneous.
Tar and Marble have capital letters for node and lowercase for stairs.
I found idiot the capital letters on Adobe, Roofing.

2 commit:
Delete all old code for moreblocks and bbstairs.
Add one function for create node and stairs. 
A function create node
Delete groups usless for stairs and moreblocks.
Create stairs or moreblocks

3 commit : 
Alias for old bbstairs.

4 commit : 
Alias for adobe and roofing rename.

My best friend for english is google translate.
Sorry for rough English.

**Comment by VanessaE** [comment]
> The renaming is to make the whole homogeneous.

For historical reasons, I prefer that you leave node names as they are.  It's okay to add aliases with "proper" text case, however.

I think I understand what you're doing now.  I will accept the rest if you'll just undo the case changes.

> And Building Block is a hell for read

That much is true.  Blame sdzen :-)

**Comment by Jat15** [comment]
Finish!

For next pull request, i will cutting mod by file : 
- alias
- node_stairs (Node and node cutting) 	
- other (craft items, tool)	
- recipes (Craft, cooking, fuel)

One commit for one file.

**Pull request merged**
