### PR TITLE
Don't set paramtype="light" by default, unless it's expectable to propagate light.

### PR DESCRIPTION
**Pull request by t4im**
See https://github.com/minetest-mods/xdecor/issues/61 which also affects homedecor.

### CODE REVIEW

**Comment by sofar** [comment]
I feel like I've seen this before... :)

:+1:

**Comment by VanessaE** [comment]
You will want to double-check that.  If you don't set `paramtype="light"`, the object will start out pitch black until something else happens next to it to change the lighting, even if it's just an opaque, solid block.

**Comment by t4im** [comment]
Interesting. I've only seen that with the book shelve yet.

With which nodes does that happen? I don't seem to be able to reproduce this here; neither with newly placed nodes nor those placed before the change. The dishwasher for example has the light type removed, yet seems to behave as expected.

**Comment by t4im** [comment]
I could reproduce this, but only with a nodebox node that had the flag removed. Those are exempt here though and get the light type set (because most of those nodes are not solid anyway)

**Comment by t4im** [comment]
Added some manual exceptions for visual consistency.

**Comment by VanessaE** [comment]
As I recall it also happens if you redefine some normal node to change its drawtype after that node has been placed in the world. For example, the old "3dforniture" mod included a round tree trunks feature (built with nodeboxes); trees would sometimes be pitch black, especially in newly-generated areas, until you did something near them.  Same was true with my mesh-based round trees mod.

**Comment by t4im** [comment]
Ok, that kinda cobbles, yea :-/

Do you think, it's better keeping stuff light-paramed for now?
This would probably something for the engine to fix, but, i guess, you're the last person i need to point out, how that will go.

**Comment by VanessaE** [comment]
I'm not against stripping that setting off of nodes that don't need it, but I think it'll be less likely to break things if we just left it turned on for all nodes, unless a specific node needs it turned off (or set to something else than "light" anyway).

**Comment by sofar** [comment]
needs resolution. PR is 3 months old and either needs rebase or closing.

**Comment by VanessaE** [comment]
I suggest closing (sorry, @t4im).  Better to keep the existing behavior and turn it off for some node or another if it's needed.

**Pull request closed without merging**
