### PR TITLE
Tranlation to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by afmachado**
Now I think I have rebased =D

### CODE REVIEW

**Comment by VanessaE** [comment]
Nope, now you have rebase markers scattered throughout the changes.  I suggest you delete homedecor, re-clone it fresh, and start over from scratch.

**Comment by afmachado** [comment]
ok, gonna do it

**Comment by afmachado** [comment]
The filename should be pt.po or pt_BR.po?

**Comment by VanessaE** [comment]
I guess pt_BR.po is correct.

**Comment by VanessaE** [comment]
What's the disposition of this pull request?

**Comment by afmachado** [comment]
Hey, what do you mean? It is a translation to the Brazilian Language. Sorry for doing it in the wrong way, I will probably close this one and make a new.

**Comment by VanessaE** [comment]
I meant, did you plan to fix this.  I guess that's a 'yes', and I would recommend starting over with a clean clone of homedecor.

**Pull request closed without merging**
